### ISSUE TITLE
Create link to dialogflow agent

### ISSUE THREAD

**Issue by koojozsef** [ThaZsomiProdzsekt/Management#1]

**Comment by Jugis** [comment]
Everyone should create this link then add it to the wiki page.

**Comment by Jugis** [comment]
HERE IS THE TUTORIAL FOR SHARING DIALOGFLOW AGENTS:
https://dialogflow.com/docs/agents/share

**Comment by koojozsef** [comment]
not done

**Comment by koojozsef** [comment]
done again
